### ISSUE TITLE
Test runner fails hello world

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/zig-test-runner#21]
I've been working to get the Zig test runner working, which seems to be one of the last (perhaps _the_) things that need to be done before we can launch. I get the following error:

```bash
We received the following error when we ran your code:
/opt/zig/lib/std/Thread/Mutex.zig:99:17: error: unable to evaluate constant expression
        switch (@atomicRmw(State, &m.state, .Xchg, .locked, .Acquire)) {
                ^
/opt/zig/lib/std/Thread/Mutex.zig:50:26: note: called from here
    return m.impl.acquire();
                         ^
/opt/zig/lib/std/debug.zig:65:38: note: called from here
    const held = stderr_mutex.acquire();
                                     ^
/opt/zig/lib/std/testing.zig:389:14: note: called from here
        print("
====== expected this output: =========
", .{});
             ^
./test_hello_world.zig:9:44: note: called from here
    comptime try testing.expectEqualStrings(expected, actual);
                                           ^
./test_hello_world.zig:6:15: note: called from here
test "say hi" {
              ^
/opt/zig/lib/std/Thread/Mutex.zig:50:26: note: referenced here
    return m.impl.acquire();
                         ^
/opt/zig/lib/std/debug.zig:65:38: note: referenced here
    const held = stderr_mutex.acquire();
                                     ^
/opt/zig/lib/std/testing.zig:389:14: note: referenced here
        print("
====== expected this output: =========
", .{});
             ^
./test_hello_world.zig:9:44: note: referenced here
    comptime try testing.expectEqualStrings(expected, actual);
```

Any thoughts?

**Comment by ErikSchierboom** [comment]
I've also tried to upgrade to the latest Zig version in https://github.com/exercism/zig-test-runner/pull/20, but that has other issues.

**Comment by hiljusti** [comment]
I would really, really love to see Zig on Exercism

Sorry, I've been meaning to get to this and other issues. I'll try to get to them as soon as possible, but between work and a new baby I can't really commit to an exact time

**Comment by ErikSchierboom** [comment]
No worries. Maybe someone else will find the time.

**Comment by suraj-mandal** [comment]
Hi @ErikSchierboom I am starting to work on this issue. I ran the ./run-tests-in-docker.sh for testing the sample test cases as present in the test folder and they seem to be working without any issues.

**Comment by suraj-mandal** [comment]
Can you please help me in figuring out the steps to take so that I can reproduce the issue? Meanwhile I am also trying them out on my own.. Your input will be helpful. Thanks

**Comment by ErikSchierboom** [comment]
@suraj-mandal Thanks for wanting to help! @ee7 is helping us upgrade the exercise to v0.10.1, so once that is done I'll recheck if this is still an issue. See https://github.com/exercism/zig-test-runner/pull/20 for the PR

**Comment by suraj-mandal** [comment]
Hi! 

I added this test to the examples-success folder for testing hello-world 

```Zig
test "Hello, World should be printed" {
    comptime try testing.expect(mem.eql(u8, leap.hello(), "Hello, World"));
}
```
and then run the script `run-tests-in-docker.sh`, and it was successful.

Is the error coming specifically from this hello-world testing or something related with zig version?

**Comment by suraj-mandal** [comment]
[
![image](https://user-images.githubusercontent.com/23192674/216577034-60094b2b-81d7-475b-928b-824f655d77f0.png)
](url)

This is the result upon running the **tests**.

**Comment by ErikSchierboom** [comment]
@suraj-mandal Well, that's not a representative test unfortunately. If you want to test it, you can do `./bin/run-in-docker.sh hello-world /path/to/hello-world /path/to/hello-world` and then point the path to hello world to the hello-world exercise from the Zig repo: https://github.com/exercism/zig/tree/main/exercises/practice/hello-world

**Comment by suraj-mandal** [comment]
got it. thanks

**Comment by suraj-mandal** [comment]
Got the issue now. I have installed zig 0.10.1 in my system and when I entered the command `zig test test_hello_world.zig` directly inside the hello-world I got the issue.

Also I confirmed the same upon executing the test runner with the given details and it is also giving the same error.

**Comment by suraj-mandal** [comment]
Hi! @ErikSchierboom was able to pass the hello-world test. In exercism/zig folder I changed the tests to:

```zig
const std = @import("std");
const mem = @import("std").mem;

const testing = std.testing;

const hello_world = @import("hello_world.zig");


test "Hello, World should be printed" {
    comptime try testing.expect(mem.eql(u8, hello_world.hello(), "Hello, World!"));
}
```

whereas previously it was:

```zig
const std = @import("std");
const testing = std.testing;

const hello_world = @import("hello_world.zig");

test "say hi" {
    const expected = "Hello, world!";
    const actual = comptime hello_world.hello();
    comptime try testing.expectEqualStrings(expected, actual);
}
```

Can you please make this change to the local exercism/zig folder and see if you are able to pass the test?

I tested this with the script as well as used the command `zig test` and both were passing.

Below are the screenshots of running:

![image](https://user-images.githubusercontent.com/23192674/216594288-2d5752b1-8397-4ee2-9e75-4e6eed63ac75.png)

Also, Here is the screenshot of the running the docker script
![image](https://user-images.githubusercontent.com/23192674/216594460-dfe1fffc-a806-4126-bc12-15f7797c4208.png)

**results.json**
![image](https://user-images.githubusercontent.com/23192674/216594541-b92fa2e1-1cde-42da-b319-69059f94990e.png)

**Comment by suraj-mandal** [comment]
One issue I found is that, `testing.expectEqualStrings` works correctly when both the strings are equal but it throws an error whenever the string lengths are different for zig 0.10. This should be mentioned, I guess..

**Comment by ErikSchierboom** [comment]
@ee7 Thoughts?

**Comment by suraj-mandal** [comment]
Thanks!
