### ISSUE TITLE
ci: can fail due to non-deterministic error messages

### ISSUE THREAD

**Issue by ee7** [exercism/zig-test-runner#26]
CI passed on PR https://github.com/exercism/zig-test-runner/pull/20, but the same workflow [failed at merge time](https://github.com/exercism/zig-test-runner/actions/runs/4085274987/jobs/7043031498).

Follow-up to https://github.com/exercism/zig-test-runner/pull/25#issuecomment-1419111333.

~I'll take a look at this.~ Edit: someone else can take this one, if interested.

**Comment by booniepepper** [comment]
I got this

**Comment by booniepepper** [comment]
May be fixed by https://github.com/exercism/zig-test-runner/pull/42/commits/11f1e5858674453593302e9c99cd18e214b8d2de
